# Google Appstore EDA

In [3]:
# Import libraries
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [4]:
# Load The Data Set
df = pd.read_csv('../data_set/googleplaystore.csv')

In [5]:
# Run automatic EDA
# comment these code if you want to auto EDA
# import ydata_profiling as yd
# profile = yd.ProfileReport(df)
# profile.to_file(output_file="../outputs/05_google_appstore.html")

In [6]:
# check the data 

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10840 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  int64
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10841 non-null  object
 9   Genres          10840 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10839 non-null  object
dtypes: float64(1), int64(1), object(11)
memory usage: 1.1+ MB

In [7]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10488,FJ WiFi HDD,TOOLS,NaN,40,2.4M,"5,000+",Free,0,Everyone,Tools,"October 31, 2017",1.0.5,2.1 and up
6194,mySugr: the blood sugar tracker made just for you,MEDICAL,4.6,21187,35M,"1,000,000+",Free,0,Everyone,Medical,"July 23, 2018",3.52.0,5.0 and up
4331,Lie Detector,FAMILY,3.1,306,2.9M,"50,000+",Free,0,Everyone,Simulation,"April 4, 2017",1.2.1,4.0.3 and up
10356,Curso Básico y Avanzado la Fe de Jesús Audio-T...,FAMILY,NaN,0,11M,10+,Free,0,Everyone 10+,Education,"July 12, 2018",1.0,4.0 and up
7113,CBRadioTab,TOOLS,3.9,127,1.5M,"50,000+",Free,0,Everyone,Tools,"April 1, 2017",1.0,3.0 and up
9292,Agenda EF,FAMILY,3.4,79,33M,"5,000+",Free,0,Everyone,Education,"May 27, 2015",1.03,3.0 and up
10090,EY Divest,BUSINESS,NaN,0,54M,5+,Free,0,Everyone,Business,"July 11, 2017",1.0.0,4.0 and up
3718,daily News,NEWS_AND_MAGAZINES,4.5,26411,26M,"1,000,000+",Free,0,Everyone,News & Magazines,"March 26, 2018",2.3.2,4.1 and up
7048,bz Basellandschaftliche News,NEWS_AND_MAGAZINES,2.8,33,33M,"1,000+",Free,0,Everyone,News & Magazines,"June 6, 2018",1.4.0,5.0 and up
10555,FK Jonava,SPORTS,NaN,1,26M,5+,Free,0,Everyone,Sports,"February 21, 2018",1.0,4.1 and up

In [9]:
df.describe()

            Rating       Reviews
count  9367.000000  1.084100e+04
mean      4.191513  4.441119e+05
std       0.515735  2.927629e+06
min       1.000000  0.000000e+00
25%       4.000000  3.800000e+01
50%       4.300000  2.094000e+03
75%       4.500000  5.476800e+04
max       5.000000  7.815831e+07

# write all the numberic variable and make them numeric

In [1]:
# import numpy as np

# # Function to convert 'Size' column to numeric values
# def convert_size(size):
#     if 'M' in size:
#         return float(size.replace('M', '')) * 1_000_000
#     elif 'k' in size:
#         return float(size.replace('k', '')) * 1_000
#     elif size == 'Varies with device':
#         return np.nan
#     else:
#         return float(size)

# # Clean 'Installs' column by removing '+' and ',' and converting to integer
# df['Installs'] = df['Installs'].str.replace('[+,]', '', regex=True).astype(int)

# # Clean 'Price' column by removing '$' and converting to float
# df['Price'] = df['Price'].str.replace('$', '').astype(float)

# # Apply the 'convert_size' function to the 'Size' column
# df['Size'] = df['Size'].apply(convert_size)

# # Check the updated datatypes and a few rows to confirm changes
# df.info()

In [2]:
df.head()

NameError: name 'df' is not defined